product:
    resource: "@OptimeBundle/Router/product_router/product_router.yml"
    prefix:   /product

category:
    resource: "@OptimeBundle/Router/product_router/category_router.yml"
    prefix:   /category