create_product:
    path:      /createproduct
    defaults:  { _controller: OptimeBundle:Product:createProduct }
    methods:   [POST]

list_product:
    path:      /listproduct
    defaults:  { _controller: OptimeBundle:Product:listProduct }
    methods:   [GET]

delete_product:
    path:      /deleteproduct/{id}
    defaults:  { _controller: OptimeBundle:Product:deleteProduct }

search_product:
    path:      /searchproduct
    defaults:  { _controller: OptimeBundle:Product:searchProduct }
    methods:   [POST]
